/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AntijnvanderGun (https://sketchfab.com/AntijnvanderGun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-ww1-plane-c4edeb0e410f46e8a4db320879f0a1db
Title: Stylized WW1 Plane
*/

import React, { useEffect, useRef } from 'react'

import planeScene from '../assets/3d/plane.glb'
import { useAnimations, useGLTF } from '@react-three/drei'

const Plane = ({ isRotating, ...props }) => {
    const ref = useRef();
    const { scene, animations } = useGLTF(planeScene)
    const { actions } = useAnimations(animations, ref);

    useEffect(() => {
        actions['Take 001'].play();
    }, [actions, isRotating])
  return (
    <mesh {...props} ref={ref}>
      <primitive object={scene} />
    </mesh>
  )
}

export default Plane